const auth = document.querySelector('#auth');
const app = document.querySelector('#app');
const signin = document.querySelector('#signin-form');
const signup = document.querySelector('#signup-form');
const toast = document.querySelector('#toast');
const authLayoutStyles = document.createElement('style');
authLayoutStyles.textContent = `@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');.auth-page{position:relative;grid-template-columns:minmax(320px,440px);justify-content:center;align-content:center;overflow:hidden}.auth-page:before{content:'';position:absolute;inset:0;background-image:linear-gradient(rgba(22,138,131,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(22,138,131,.04) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.8),transparent 82%);pointer-events:none}.auth-page:after{content:'';position:absolute;width:220px;height:220px;left:8%;top:12%;border-radius:45% 55% 62% 38%;background:linear-gradient(135deg,#ffd56a,#f38d65);opacity:.7;filter:blur(1px);transform:rotate(-18deg);pointer-events:none}.auth-card{display:block;position:relative;z-index:1;width:100%;padding:30px 32px;background:rgba(255,255,255,.96);border:1px solid var(--line);border-radius:14px;box-shadow:0 18px 45px rgba(31,57,69,.09);animation:rise .5s ease both}.auth-card>.logo-box{justify-content:center;margin:0 0 28px}.auth-card form{position:relative;width:100%;height:fit-content;margin:0;border:0;padding:0;box-shadow:none;background:transparent}.auth-card form p{margin-bottom:0}.auth-card form[hidden]{display:none!important}#signup-form h1:after{content:'Create an account for your organization.'}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@media(max-width:800px){.auth-page{grid-template-columns:minmax(280px,440px);align-content:center}.auth-page:after{left:-90px;top:16%;width:180px;height:180px}}`;
document.head.appendChild(authLayoutStyles);
const backgroundArt = document.createElement('div');
backgroundArt.className = 'background-art';
backgroundArt.innerHTML = '<span class="art-ring"></span><span class="art-blob"></span><span class="art-dots"></span><span class="art-spark">+</span>';
document.querySelector('#auth').appendChild(backgroundArt);
const artStyles = document.createElement('style');
artStyles.textContent = `.background-art{position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:0}.background-art span{position:absolute;display:block}.art-ring{width:290px;height:290px;right:7%;top:7%;border:28px solid rgba(77,166,190,.2);border-radius:50%;box-shadow:0 0 0 15px rgba(255,255,255,.5),0 0 0 42px rgba(238,139,75,.08);transform:rotate(18deg)}.art-blob{width:190px;height:250px;right:12%;bottom:-70px;border-radius:55% 45% 30% 70%;background:linear-gradient(145deg,rgba(22,138,131,.2),rgba(92,157,207,.13));transform:rotate(32deg)}.art-dots{width:130px;height:130px;left:7%;bottom:8%;background-image:radial-gradient(rgba(22,138,131,.38) 2px,transparent 2px);background-size:18px 18px;mask-image:linear-gradient(135deg,transparent 4%,#000 42%,transparent 90%);transform:rotate(-12deg)}.art-spark{right:24%;top:25%;font:500 70px/1 'Space Grotesk',Arial,sans-serif;color:rgba(238,139,75,.5);transform:rotate(18deg)}.auth-card form,.auth-card>.logo-box{z-index:1}@media(max-width:800px){.art-ring{width:190px;height:190px;right:-70px;top:2%;border-width:20px}.art-blob{right:-40px;width:150px;height:190px}.art-spark{right:8%;top:18%;font-size:48px}.art-dots{left:-20px;bottom:4%}}`;
document.head.appendChild(artStyles);
const compactAuthStyles = document.createElement('style');
compactAuthStyles.textContent = `@media (min-width:801px) and (max-height:900px){.auth-card{padding:23px 28px}.auth-card>.logo-box{margin-bottom:20px}.auth-card form{gap:10px}.auth-card form{margin-top:18px}.auth-card h1{font-size:25px}.auth-card h1:after{margin-top:6px;font-size:13px}.auth-card label{gap:5px;font-size:11px}.auth-card input{padding:8px 10px}.auth-card .purple{padding:10px 20px}.auth-card p{margin-top:10px}}`;
document.head.appendChild(compactAuthStyles);
const show = id => { document.querySelectorAll('.view').forEach(view => view.classList.toggle('active', view.id === id)); document.querySelector('#view-title').textContent = id === 'profile' ? 'Employee Profile' : id[0].toUpperCase() + id.slice(1); };
const openApp = message => { auth.hidden = true; app.hidden = false; show('employees'); if (message) notify(message); };
signup.hidden = true;
document.querySelector('#show-signup').onclick = () => { signin.hidden = true; signup.hidden = false; };
document.querySelector('#show-signin').onclick = () => { signup.hidden = true; signin.hidden = false; };
signin.onsubmit = event => { event.preventDefault(); openApp(); };
signup.onsubmit = event => { event.preventDefault(); openApp('Account created. Your employee login ID is OTJODO02320001.'); };
document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => show(button.dataset.view));
document.querySelector('#logout').onclick = () => { app.hidden = true; auth.hidden = false; window.scrollTo(0, 0); };
document.querySelectorAll('.open-profile').forEach(button => button.onclick = () => show('profile'));
document.querySelector('#add-employee').onclick = () => notify('Employee creation form is ready for the next sprint.');
document.querySelector('#apply-leave').onclick = () => notify('Leave application form opened for the Employee view.');
document.querySelectorAll('.approve,.reject').forEach(button => button.onclick = () => { const row = button.closest('.leave-row'); const approved = button.classList.contains('approve'); row.querySelector('.status').textContent = approved ? 'Approved' : 'Rejected'; row.querySelector('.status').className = `status ${approved ? '' : 'pink'}`; button.remove(); notify('Leave request decision saved.'); });
function notify(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
