const auth = document.querySelector('#auth');
const app = document.querySelector('#app');
const signin = document.querySelector('#signin-form');
const signup = document.querySelector('#signup-form');
const toast = document.querySelector('#toast');
const authLayoutStyles = document.createElement('style');
authLayoutStyles.textContent = `@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');.auth-page{position:relative;grid-template-columns:repeat(2,minmax(300px,360px));grid-template-areas:'brand brand' 'signin signup';justify-content:center;align-content:center;gap:22px;overflow:hidden}.auth-page:before{content:'';position:absolute;inset:0;background-image:linear-gradient(rgba(22,138,131,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(22,138,131,.04) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.8),transparent 82%);pointer-events:none}.auth-page:after{content:'';position:absolute;width:220px;height:220px;left:8%;top:12%;border-radius:45% 55% 62% 38%;background:linear-gradient(135deg,#ffd56a,#f38d65);opacity:.7;filter:blur(1px);transform:rotate(-18deg);pointer-events:none}.auth-card{display:contents}.auth-card>.logo-box{grid-area:brand;justify-content:center;margin:0;position:relative;z-index:1}.auth-card form{position:relative;z-index:1;width:100%;height:fit-content;margin:0;background:rgba(255,255,255,.96);border:1px solid var(--line);border-radius:14px;padding:30px 32px;box-shadow:0 18px 45px rgba(31,57,69,.09);animation:rise .5s ease both}.auth-card form:nth-of-type(1){grid-area:signin}.auth-card form:nth-of-type(2){grid-area:signup;animation-delay:.08s}.auth-card form p{margin-bottom:0}.auth-card form[hidden]{display:grid!important}#signup-form h1:after{content:'Create an account for your organization.'}.signup-toggle{display:none}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@media(max-width:800px){.auth-page{grid-template-columns:minmax(280px,440px);grid-template-areas:'brand' 'signin' 'signup';align-content:start;overflow:auto}.auth-card>.logo-box{grid-area:brand;margin-top:10px}.auth-card form{margin-bottom:18px}.auth-page:after{left:-90px;top:16%;width:180px;height:180px}}`;
document.head.appendChild(authLayoutStyles);
const show = id => { document.querySelectorAll('.view').forEach(view => view.classList.toggle('active', view.id === id)); document.querySelector('#view-title').textContent = id === 'profile' ? 'Employee Profile' : id[0].toUpperCase() + id.slice(1); };
const openApp = message => { auth.hidden = true; app.hidden = false; show('employees'); if (message) notify(message); };
signup.hidden = false;
signup.classList.add('collapsed');
const signupToggle = document.createElement('button');
signupToggle.type = 'button';
signupToggle.className = 'signup-toggle';
signupToggle.textContent = 'Show sign up form ↓';
signup.insertBefore(signupToggle, signup.querySelector('label'));
signupToggle.onclick = () => { signup.classList.toggle('collapsed'); signupToggle.textContent = signup.classList.contains('collapsed') ? 'Show sign up form ↓' : 'Hide sign up form ↑'; };
const signupStyles = document.createElement('style');
signupStyles.textContent = `.signup-toggle{display:block;width:100%;background:var(--mint);border:1px solid #bce1da;color:var(--teal);border-radius:6px;padding:11px;font-weight:700}.auth-card form.collapsed label,.auth-card form.collapsed .purple,.auth-card form.collapsed p{display:none}.auth-card form.collapsed{min-height:185px}.auth-card form.collapsed .signup-toggle{margin-top:24px}`;
document.head.appendChild(signupStyles);
document.querySelector('#show-signup').onclick = () => signup.scrollIntoView({ behavior: 'smooth', block: 'center' });
document.querySelector('#show-signin').onclick = () => signin.scrollIntoView({ behavior: 'smooth', block: 'center' });
signin.onsubmit = event => { event.preventDefault(); openApp(); };
signup.onsubmit = event => { event.preventDefault(); openApp('Account created. Your employee login ID is OTJODO02320001.'); };
document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => show(button.dataset.view));
document.querySelector('#logout').onclick = () => { app.hidden = true; auth.hidden = false; window.scrollTo(0, 0); };
document.querySelectorAll('.open-profile').forEach(button => button.onclick = () => show('profile'));
document.querySelector('#add-employee').onclick = () => notify('Employee creation form is ready for the next sprint.');
document.querySelector('#apply-leave').onclick = () => notify('Leave application form opened for the Employee view.');
document.querySelectorAll('.approve,.reject').forEach(button => button.onclick = () => { const row = button.closest('.leave-row'); const approved = button.classList.contains('approve'); row.querySelector('.status').textContent = approved ? 'Approved' : 'Rejected'; row.querySelector('.status').className = `status ${approved ? '' : 'pink'}`; button.remove(); notify('Leave request decision saved.'); });
function notify(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
